version: '3.1'
services:
  mongo-dbserver:
    image: mongo
    ports:
      - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=pass123
    volumes:
      - mongo-data:/data/db
  mongo-client:
    image: mongo-express:0.44
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass123
      - ME_CONFIG_MONGODB_SERVER=mongo-dbserver
volumes:
  mongo-data:
    driver: local
